### ISSUE TITLE
class Thread doesn't exist

### ISSUE THREAD

**Issue by Creeperface01** [PEMapModder/PocketMine-Wrapper#2]
PHP Fatal error:  Class 'Thread' not found in /home/matej/minetox/php/functions.php on line 14

**Comment by PEMapModder** [comment]
Use PHP binaries with pthreads extension. You can use the PocketMine PHP binaries for this if you aren't sure how to install pthreads into your default PHP binaries.

**Comment by Creeperface01** [comment]
Si what yould i run? (ubuntu) 
i ran php path

**Comment by PEMapModder** [comment]
Use the PHP path for an installed PocketMine version of binaries. This script starts a server process using the same PHP binaries as the one it is launched with (`PHP_BINARY`)
