### ISSUE TITLE
"Not Responding" issue

### ISSUE THREAD

**Issue by AvivShopen** [PEMapModder/PocketMine-Wrapper#3]
when the server stop, its sending me "Not Responding" message and I need to click X to start again, I want that my server auto restart without always clicking the X button, can you help? thx and sorry on bad english

**Comment by PEMapModder** [comment]
Please provide more information. On my tests it works well if you repeat for infinite times.

**Comment by AvivShopen** [comment]
I have some screenshot to show you...
![screenshot 2015-11-25 22-14-21](https://cloud.githubusercontent.com/assets/16016788/11408529/6cd12bcc-93c2-11e5-8950-a80b23ba4114.jpg)
and I need to click the X button to restart... any way to fix?

**Comment by AvivShopen** [comment]
plugins using: 
1vs1 v0.0.3, ArtificialIntelligent v0.1, BasicHUD v1.0.6, Boat v1.1, BulkCommands v1.0-build#007, CallOfDutyNawaf1b v1.0, ClearLagg v1.1.0, CombatLogger v1.2.0, CustomAlerts v1.6, DevTools v1.10.0, EconomyAPI v2.0.9, EconomyPShop v2.0.2, EconomySell v2.0.7, EconomyShop v2.0.7, EnderPearl v1.2.3, EssentialsPE v1.1.0, FactionsPro v1.3.2, GiveKey v1.1_Beta, iControlU v1.3, iManager v1.1.0, iProtector v3.1a, ItemCloud v1.3, LaunchPads v1.0.0, Lightning vBeta-1, ManyWorlds v2.0.3, MegaTroll v1.0.0, MineReset v2.1, MultiTP v1.0.0, NoArrowPick v1, PlayHarder v1.0-TEST, PrizeWin v1.0.6, PurePerms v1.1.12, RestartMe v1.1.0, ServerMail v0.0.2, SignStatus v2.1, SimpleAuth v1.8.1, Slapper v1.2.5, TapToDo v2.2.1, VanishNP v1.0.0, WorldEditArt v1.0.0_beta_dev_#048, xRulesx v1.0.0, PureChat v1.3.0, SimpleAuthHelper v2.0.4, SimpleWarp v2.1.0, WarpSigns v0.0.1, CrateKeys v1.0

**Comment by PEMapModder** [comment]
Well, first of all, ImagicalCorp/PocketMine-0.13.0 is not supported here.

**Comment by AvivShopen** [comment]
oh ok I understand:), I will wait for official and maybe that will support

**Comment by PEMapModder** [comment]
Try the official bleeding build.

**Comment by AvivShopen** [comment]
I have the same problem and now after 1-2 minutes I start the server, the server doesn't showing me messages like a lag...... and players cant chat and at the end they disconnecting and they cant get in anymore....

**Comment by PEMapModder** [comment]
I have no idea.
