### ISSUE TITLE
Shutting down server incorrectly leads to this

### ISSUE THREAD

**Issue by ifvictr** [PEMapModder/PocketMine-Wrapper#4]
If you start your server with this script and you shut it down incorrectly(not using `-kill`, `-die`, `/stop`, etc., just shut down by pressing the exit button), for about 20 minutes upon incorrectly shutting it down, you won't be able to restart the server on the same port. Is there anyway to fix this?

**Comment by PEMapModder** [comment]
Does this issue happen if you directly close the server?
I'm thinking about using register_shutdown_function()

**Comment by ifvictr** [comment]
What do you mean by directly closed? If pressing the x button(on Windows) is considered that, then yes.

**Comment by PEMapModder** [comment]
I mean on normal PocketMine Windows installation.

**Comment by ifvictr** [comment]
Yes, on both. If you started the server using the terminal, and you exit out by pressing "x", or you started the server using the regular start script(but sill using this script) and exit out by pressing "x", it'll happen.

**Comment by PEMapModder** [comment]
I don't think it is possible to fix this if it can't get fixed in vanilla PocketMine.

**Comment by ifvictr** [comment]
It only happens when I use this script. When you just run PocketMine the normal way, this doesn't happen. However, when you use this script and you exit the server by just pressing "x", it'll happen.
