### ISSUE TITLE
Console colors

### ISSUE THREAD

**Issue by ifvictr** [PEMapModder/PocketMine-Wrapper#5]
Would it be possible for you to add support for colors on the console? Because right now it's just gray text for everything.

**Comment by PEMapModder** [comment]
The script echos output from PocketMine as-is. If colors do not exist, try launching this script using MinTTY?

**Comment by PEMapModder** [comment]
Does it work if you start the script with the argument --enable-ansi?

**Comment by ifvictr** [comment]
How would you do that? Both of them?

**Comment by PEMapModder** [comment]
Try running the server using mintty. look at start.cmd for how.
